### ISSUE TITLE
cloning repository: Permission denied

### ISSUE THREAD

**Issue by gtom** [mruby-esp32/mruby-esp32-app-mirb#2]
Hi,
I have an issue cloning app-mirb:

```
git clone --recursive https://github.com/mruby-esp32/mruby-esp32-app-mirb.git
Klone nach 'mruby-esp32-app-mirb' ...
remote: Counting objects: 48, done.
remote: Total 48 (delta 0), reused 0 (delta 0), pack-reused 48
Entpacke Objekte: 100% (48/48), Fertig.
Prüfe Konnektivität ... Fertig.
Submodul 'components/mruby/mruby' (git@github.com:mruby/mruby.git) für Pfad 'components/mruby/mruby' in die Konfiguration eingetragen.
Klone nach 'components/mruby/mruby' ...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: Klonen von 'git@github.com:mruby/mruby.git' in Submodul-Pfad 'components/mruby/mruby' fehlgeschlagen
```
Perhaps you can fix this?
Thanks in advance

**Comment by pandax381** [comment]
Thank you for reporting the problem.

It seems to be because SSH is used as a protocol to obtain submodule.

The easiest way to deal with it's to configure yourself to have SSH access to GitHub.

But, I tried not to cause problems even if you did not make that setting.
I replaced submodule protocol using HTTPS instead of SSH. (8c77f6b93ba0704d892906a90367bc64f9ecdcdb)

Please try again.

**Comment by gtom** [comment]
It works. 
I will start playing around with mirb.
Thank you for your very fast response.
